n_layers: 2
n_heads: 2
hidden_size: 300
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'

item_drop_ratio: 0.2
item_drop_coefficient: 0.9
lambda: 1e-3

train_stage: inductive_ft  # pretrain / inductive_ft / transductive_ft

plm_suffix: blair-roberta-base.feature
plm_size: 768
adaptor_layers: [768,300]

# plm_suffix: blair-roberta-large.feature
# plm_size: 1024
# adaptor_layers: [1024,300]


adaptor_dropout_prob: 0.2
temperature: 0.07
n_exps: 8

